# Generated by Django 3.1.6 on 2021-02-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjournal',
            name='calories',
            field=models.IntegerField(),
        ),
    ]
