# Generated by Django 3.1.6 on 2021-02-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0002_auto_20210207_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjournal',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
