# Generated by Django 3.1.6 on 2021-02-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0003_auto_20210207_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjournal',
            name='calories',
            field=models.IntegerField(null=True),
        ),
    ]
