# Generated by Django 3.1.6 on 2021-02-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0004_auto_20210207_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjournal',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
