# Generated by Django 3.1.6 on 2021-02-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0006_auto_20210207_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodjournal',
            name='food_log_item',
        ),
        migrations.AddField(
            model_name='foodlogitem',
            name='food_journal_entry',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='foodjournal.foodjournal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodjournal',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='foodjournal.user'),
            preserve_default=False,
        ),
    ]
