# Generated by Django 3.1.6 on 2021-02-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0007_auto_20210207_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlogitem',
            name='food_journal_entry',
        ),
    ]
