# Generated by Django 3.1.6 on 2021-02-09 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0008_remove_foodlogitem_food_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodjournal',
            name='food_log_item',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='foodjournal.foodlogitem'),
            preserve_default=False,
        ),
    ]
