# Generated by Django 3.1.6 on 2021-02-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0009_foodjournal_food_log_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodjournal',
            name='food_log_item',
        ),
        migrations.AddField(
            model_name='foodlogitem',
            name='entry',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_items', to='foodjournal.foodjournal'),
            preserve_default=False,
        ),
    ]
