# Generated by Django 3.1.6 on 2021-02-11 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0011_auto_20210211_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlogitem',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_items', to='foodjournal.foodjournal'),
        ),
    ]
