# Generated by Django 3.1.6 on 2021-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0013_auto_20210211_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjournal',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
