# Generated by Django 3.1.6 on 2021-02-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0027_auto_20210211_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodjournal',
            name='items',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='foodjournal.foodlogitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodlogitem',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
