# Generated by Django 3.1.6 on 2021-02-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0028_auto_20210211_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlogitem',
            name='entry',
        ),
    ]
