# Generated by Django 3.1.6 on 2021-02-11 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0029_remove_foodlogitem_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjournal',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='foodjournal.foodlogitem'),
        ),
    ]
