# Generated by Django 3.1.6 on 2021-02-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0031_auto_20210211_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlogitem',
            name='calories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='foodlogitem',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
