# Generated by Django 3.1.6 on 2021-02-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0032_auto_20210211_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlogitem',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
