# Generated by Django 3.1.6 on 2021-02-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0033_auto_20210211_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodjournal',
            name='items',
        ),
        migrations.AddField(
            model_name='foodlogitem',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to='foodjournal.foodjournal'),
        ),
    ]
