# Generated by Django 3.1.6 on 2021-02-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0034_auto_20210211_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjournal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodjournal.user'),
        ),
    ]
