# Generated by Django 3.1.6 on 2021-02-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0035_auto_20210211_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlogitem',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodlogitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
