# Generated by Django 3.1.6 on 2021-02-11 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0037_auto_20210211_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjournal',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodlogitem',
            name='entry',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to='foodjournal.foodjournal'),
            preserve_default=False,
        ),
    ]
