# Generated by Django 3.1.6 on 2021-02-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0038_auto_20210211_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodjournal',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='foodlogitem',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
