# Generated by Django 3.1.6 on 2021-02-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0039_auto_20210211_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlogitem',
            name='date',
        ),
    ]
