# Generated by Django 3.1.6 on 2021-02-12 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0040_remove_foodlogitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlogitem',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to='foodjournal.foodjournal'),
        ),
    ]
