# Generated by Django 3.1.6 on 2021-02-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0042_auto_20210212_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='maleOrFemale',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
