# Generated by Django 3.1.6 on 2021-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0043_auto_20210212_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
