# Generated by Django 3.1.6 on 2021-02-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0046_auto_20210213_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rec_bmr',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rec_cal_lose',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rec_calories',
            field=models.IntegerField(blank=True),
        ),
    ]
