# Generated by Django 3.1.6 on 2021-02-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjournal', '0047_auto_20210213_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rec_bmr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rec_cal_lose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rec_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
